config/routes.rb
Taxi2::Application.routes.draw do
  resources :inscriptions

  get "welcome/index"

  root 'welcome#index'

end

app/models/inscription.rb
class Inscription < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inscriptions_controller.rb
class InscriptionsController < ApplicationController
  before_action :set_inscription, only: [:show, :edit, :update, :destroy]

  # GET /inscriptions
  # GET /inscriptions.json
  def index
    @inscriptions = Inscription.all
  end

  # GET /inscriptions/1
  # GET /inscriptions/1.json
  def show
  end

  # GET /inscriptions/new
  def new
    @inscription = Inscription.new
  end

  # GET /inscriptions/1/edit
  def edit
  end

  # POST /inscriptions
  # POST /inscriptions.json
  def create
    @inscription = Inscription.new(inscription_params)

    respond_to do |format|
      if @inscription.save
        format.html { redirect_to @inscription, notice: 'Inscription was successfully created.' }
        format.json { render action: 'show', status: :created, location: @inscription }
      else
        format.html { render action: 'new' }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inscriptions/1
  # PATCH/PUT /inscriptions/1.json
  def update
    respond_to do |format|
      if @inscription.update(inscription_params)
        format.html { redirect_to @inscription, notice: 'Inscription was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @inscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inscriptions/1
  # DELETE /inscriptions/1.json
  def destroy
    @inscription.destroy
    respond_to do |format|
      format.html { redirect_to inscriptions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inscription
      @inscription = Inscription.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inscription_params
      params.require(:inscription).permit(:name, :firstname, :email, :profession, :street, :zipcode, :town)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@inscription = Inscription.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inscriptions_helper.rb
module InscriptionsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/inscriptions/_form.html.erb
<%= form_for @inscription, html: {role: "form", class: ""} do |f| %>

  <div class="form-group">
    <%= f.label :name, "Nom", class: "required" %><br>
    <%= f.text_field :name, placeholder: "MARTIN", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :firstname, "Prénom", class: "required" %><br>
    <%= f.text_field :firstname, placeholder: "Nicolas", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :email, "Email", class: "required" %><br>
    <%= f.email_field :email, placeholder: "nicolas.martin@hotmail.fr", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :profession, "Situation", class: "required" %><br>
    <%= f.select :profession, ["Artisan","Locataire","Salarié","Autre Situation","en formation","Autre profession"], prompt: "-- sélectionner voter situation --", required: true %>
  </div>
  <div class="form-group">
    <%= f.label :street, "Adresse" %><br>
    <%= f.text_area :street, placeholder: "18 rue du printemps" %>
  </div>
  <div class="form-group">
    <%= f.label :zipcode, "Code postal" %><br>
    <%= f.text_field :zipcode, placeholder: "75001" %>
  </div>
  <div class="form-group">
    <%= f.label :town, "Ville" %><br>
    <%= f.text_field :town, placeholder: "Paris" %>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Fermer</button>
    <%= f.submit "Envoyer l'inscription", class: "btn btn-success", disabled: true %>
  </div>
<% end %>

app/views/inscriptions/edit.html.erb
<h1>Editing inscription</h1>

<%= render 'form' %>

<%= link_to 'Show', @inscription %> |
<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/index.html.erb
<h1>Listing inscriptions</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Firstname</th>
      <th>Email</th>
      <th>Profession</th>
      <th>Street</th>
      <th>Zipcode</th>
      <th>Town</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @inscriptions.each do |inscription| %>
      <tr>
        <td><%= inscription.name %></td>
        <td><%= inscription.firstname %></td>
        <td><%= inscription.email %></td>
        <td><%= inscription.profession %></td>
        <td><%= inscription.street %></td>
        <td><%= inscription.zipcode %></td>
        <td><%= inscription.town %></td>
        <td><%= link_to 'Show', inscription %></td>
        <td><%= link_to 'Edit', edit_inscription_path(inscription) %></td>
        <td><%= link_to 'Destroy', inscription, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inscription', new_inscription_path %>

app/views/inscriptions/new.html.erb
<h1>New inscription</h1>

<%= render 'form' %>

<%= link_to 'Back', inscriptions_path %>

app/views/inscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @inscription.name %>
</p>

<p>
  <strong>Firstname:</strong>
  <%= @inscription.firstname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @inscription.email %>
</p>

<p>
  <strong>Profession:</strong>
  <%= @inscription.profession %>
</p>

<p>
  <strong>Street:</strong>
  <%= @inscription.street %>
</p>

<p>
  <strong>Zipcode:</strong>
  <%= @inscription.zipcode %>
</p>

<p>
  <strong>Town:</strong>
  <%= @inscription.town %>
</p>

<%= link_to 'Edit', edit_inscription_path(@inscription) %> |
<%= link_to 'Back', inscriptions_path %>

app/views/layouts/_footer.html.erb
<footer>
	<div class="container">
		<ul class="list-inline text-center">
			<li><%= "Salon des Taxis © 1998-2014" %></li>
			<li> <%= fa_icon "coffee" %> <%= link_to "Organisation Delling Expo", 'http://www.dellingexpo.com', target: "_blank" %></li>
			<li><%= fa_icon "code" %> <%= link_to "Site conçu par DIVAVEO", 'http://www.divaveo.com', target: "_blank" %></li>
			<li><%= fa_icon "legal" %> <%= link_to "Mentions", '#' %></li>
			<li> <%= fa_icon "facebook-square" %> <%= link_to "Facebook", 'http://www.facebook.com/salondestaxis', target: "_blank" %></li>
		</ul>	
	</div>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taxi2</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <script type="text/javascript" src="//use.typekit.net/qyt5oej.js"></script>
	<script type="text/javascript">try{Typekit.load();}catch(e){}</script>
  <%= csrf_meta_tags %>
</head>
<body>



	<%= render "/welcome/slide1" %>
  <%= render "/welcome/slide2" %>
  <%= render "/welcome/slide3" %>
  <%= render "/welcome/slide4" %>

  <%= render "/layouts/footer" %>
	
	<%= yield %>	



</body>
</html>

app/views/welcome/_slide1.html.erb
<div id="slide1">

	<div id="nav">
		<div id="title-logo">
			<%= link_to image_tag("logo.png"), root_path %>
		</div>
    <ul id="links">
      <li><%= link_to "Contenu du salon", '#exposants' %></li>
      <li><%= link_to "Exposer", '#exposer' %></li>
      <li><%= link_to "Venir au salon", '#venir' %></li>
      <li><%= link_to "Médias & Presse", '#contact' %></li>
    </ul>
  </div>

  <div id="nav-secondary">
    <div id="title-logo">
      <%= link_to image_tag("logo.png"), root_path  %>
    </div>
    <ul id="links">
      <li><%= link_to "Contenu du salon", '#exposants' %></li>
      <li><%= link_to "Exposer", '#exposer' %></li>
      <li><%= link_to "Venir au salon", '#venir' %></li>
      <li><%= link_to "Médias & Presse", '#contact' %></li>
    </ul>
  </div>

	<div class="jumbotron">
	  <h1>Salon des Taxis <br>
	  		31 janvier et 1er février 2015
	  </h1>
	  <p>Même les américains s'y pressent ! Vous aussi, ne manquez pas la 12ème édition du plus grand salon des professionnels du taxi en France !</p>
	  <p><a class="btn btn-danger btn-lg" role="button" data-toggle="modal" data-target="#myModal">Chauffeurs de taxis, inscrivez-vous gratuitement!</a></p>
	</div>	
</div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Inscription au Salon des Taxis 2015</h4>
      </div>
      <div class="modal-body">
        <%= render '/inscriptions/form' %>
      </div>
    </div>
  </div>
</div>

app/views/welcome/_slide2.html.erb
<div id="slide2">
	<%= link_to "", "#", name: "exposants" %>
	<div class="checkerboard">
				
	</div>

	<div id="services">
		<h1>Ce que vous trouverez au salon des taxis</h1>
		<br>
		<div id="service-map">
			<%= image_tag "services.png" %>		
			<div id="legend-car">
				<p>Vous pourrez trouver votre nouveau <strong><a href="#" class="details" data-toggle="tooltip" data-placement="right" title="Citroen, Ford, Hyundai, Mercedes, Kia, Opel, Renault, Seat ...">véhicule</a></strong> au salon grâce à la présence de la plupart des constructeurs.</p>
			</div>
			<div id="legend-luminere">
				<p>Trouvez tous les <strong><a href="#" class="details" data-toggle="tooltip" data-placement="right" title="Alpha Taxis, G7, GAMMA, Visucab, ...">équipements</a></strong> et services dont vous avez besoin : lumineux, taximètres, etc.</p>
			</div>
			<div id="legend-smartphone">
				<p>Essayez aussi toutes les dernières applications <strong><a href="#" class="details" data-toggle="tooltip" data-placement="left" title="liste des applications de smartphones ...">Smartphone</a></strong> pour la réservation en direct de courses.</p>
			</div>
			<div id="legend-meeting">
				<p>Rencontrez tous les <strong><a href="#" class="details" data-toggle="tooltip" data-placement="right" title="Liste des professionnels du secteur ...">professionnels</a></strong> du secteur et assistez à de nombreuses <a href="#">conférences</a>.</p>
			</div>
			<div id="legend-financial">
				<p>Trouvez toutes les solutions de <strong><a href="#" class="details" data-toggle="tooltip" data-placement="left" title="Liste des professionnels du secteur ...">financement</a></strong> de votre activité.</p>
			</div>
		</div>

	</div>

</div>

app/views/welcome/_slide3.html.erb
<div id="slide3">
	<%= link_to "", "#", name: "exposer" %>
	<div class="checkerboard">
		
	</div>

	<div id="panel-exposer">
		<h1>Professionnels, venez exposer au Salon des Taxis</h1>
		<h2><strong>44 400 chauffeurs</strong> de taxis depuis la première édition du salon !</h3>	
		<h3>Un salon qui fédère des clients qui lui sont fidèles au cours des Editions (75% des entreprises reviennent d'une édition sur l'autre)</p>
		<br>
		<%= image_tag "stands.png" %>
		<br>
		<div class="container">
			<h2>Les différentes formules de stands</h2>
			<h3>Chacune des formules vous donne droit à une surface d'exposition, à l'insertion d'une fiche signalétique de votre société dans le Catalogue officiel, à des badges exposants, et l'accès au Club exposants.</p>
			<br>
			<p><%= link_to "Télécharger notre offre de stands", '#', class: "btn btn-danger btn-lg" %></p>	

			<hr>
			
				<h2>Nos actions de communication</h2>

				<h3 class="text-danger">La communication mise en place</h3>	

					<div class="row">
						<div class="col-md-6">
							<h4 class="text-left"> <%= fa_icon "envelope" %> Marketing direct : Mailing + Phoning</h4>	
							<p class="text-justify">
								<ul class="list-unstyled">
									<li class="text-left"><%= fa_icon "hand-o-right" %> 60 000 Invitations envoyées à l’adresse personnelle des chauffeurs de Taxis exerçant en France, ainsi qu’à tous les groupements des professionnels du Taxi et aux centres de formation dédiés, le Salon des Taxis possède la plus grande base de données taxis en France.</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> Campagne de phoning auprès de 5000 chauffeurs en activité sélectionnés dans tous les départements français.</li>
									<li class="text-left"><%= fa_icon "hand-o-right" %> Envois d’invitations « sms » à tous les visiteurs des précédentes éditions.</li>
									<li class="text-left"><%= fa_icon "hand-o-right" %> Distribution de flyers dans les gares et les aéroports des 10 plus grandes villes françaises.</li>
									<li class="text-left"><%= fa_icon "hand-o-right" %> Messages prévenant de la tenue du salon envoyés directement dans les véhicules par les centraux-radio.</li>
									<li class="text-left"><%= fa_icon "hand-o-right" %> Animation d’une page FaceBook : « Amandine des taxis »	</li>
								</ul>
							</p>		
						</div>
						<div class="col-md-6">
							<h4 class="text-left"> <%= fa_icon "volume-up" %> Campagne Média : Presse radio, affichage</h4>	
							<p class="text-justify">
								<ul class="list-unstyled">
									<li class="text-left"><%= fa_icon "hand-o-right" %> Insertions d’encarts publicitaires dans la presse généraliste et la presse spécialisée.</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> Bannière 15m x 5m au dessus du périphérique Sud de Paris.</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> Campagne d’affichage 4 x 3 autour du Parc des Expositions.</li>
								</ul>
							</p>		
						</div>
					</div>

				<h3 class="text-danger">Exposants, offrez-vous plus de visibilité</h3>	
			
				<div class="row">
						<div class="col-md-6">
							<p class="text-justify">
								<ul class="list-unstyled">
									<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Insérez votre logo</strong> sur votre fiche signalétique du catalogue officiel</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Insérez votre publicité dans le catalogue officiel :</strong> diffusion à 5 500 exemplaires, document officiel du Salon remis personnellement à chaque visiteur à l'entrée du salon.</li>
									<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Insérez votre logo sur tous les plans du Salon :</strong> le plan est imprimé dans le catalogue officiel ainsi que sur les panneaux signalétiques placés dans des endroits stratégiques.</li>
								</ul>
							</p>		
						</div>
						<div class="col-md-6">
							<p class="text-justify">
								<ul class="list-unstyled">
									<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Faites distribuer vos documents à l'accueil par nos hôtesses :</strong> offre réservée à 2 exposants maximum, documents fournis par vos soins. Impression par nos soins possible (nous consulter).</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Parrainez une zone du Salon :</strong> vous pouvez parrainer le Bar visteur, le parking visiteurs, la garderie,...</li>
		 							<li class="text-left"><%= fa_icon "hand-o-right" %> <strong>Opération de mailing sur notre base nationale Taxi :</strong> LE fichier national des taxis (coordonnées postales) est à votre disposition. Consultez nous !</li>
								</ul>
							</p>		
						</div>
					</div>
					<br>
					<h3 class="bg-danger">Vous souhaitez avoir une visibilité plus importante? Contactez Josiane MONET au 01 41 33 08 08 ou par mail : <%= mail_to "jmonet@dellingexpo.com" %></h3>		

					<br>
			<p><%= link_to "Vous êtes intéressé ? Téléchargez le bulletin d'inscription", 'https://s3.amazonaws.com/dellingexpo/salondestaxis/docs/inscription_exposant_2015.pdf', class: "btn btn-danger btn-lg", target: "_blank" %></p>	
		</div>
		
	</div>


	
</div>

app/views/welcome/_slide4.html.erb
<div id="slide4">
<%= link_to "", "#", name: "venir" %>
	<div class="checkerboard">
			
	</div>

	<div id="venir">
		<h1>Comment venir au salon ?</h1>

		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h3 class="text-danger">Rejoignez nous les 31 janvier et 1er février 2015</h3>
					<h4 class="text-danger">de 9h30 à 18h00</h4>
					<h4 class="text-danger">PARIS - Parc des Expositions de la Porte de Versailles - HALL 5.2</h4>
					<h4>Une flotte d’autobus affrétée par nos soins (sur demande) peut être mis à votre disposition! En collaboration avec les syndicats professionnels en région, ce service optionnel facilitera le déplacement des visiteurs de province.</h4>
					<h4>La SNCF accorde une réduction de 20 % sur les billets Aller-Retour en première et deuxième classe, y compris les TGV.</h4>
					<h4>Pour recevoir votre titre de réduction, veuillez adresser votre demande à Delling Expo par mail : <%= mail_to "jmonet@dellingexpo.com" %> ou par téléphone au 01 41 33 08 08 avant le 21 janvier 2013.</h4>
				</div>
				<div class="col-md-6">
					 <%= image_tag "plan-parc-expo.png" %>
				</div>
			</div>
		</div>

	</div>

</div>